apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-ai-gateway-basic
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-ai-gateway-basic
  namespace: default
spec:
  gatewayClassName: envoy-ai-gateway-basic
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy-ai-gateway-basic
  namespace: default
spec:
  parentRefs:
  - name: envoy-ai-gateway-basic
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /v1/models
    backendRefs:
    - name: model-service
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /v1/chat
    backendRefs:
    - name: guardrails-service
      port: 8000
  - matches:
    - path:
        type: PathPrefix
        value: /v1/completions
    backendRefs:
    - name: guardrails-service
      port: 8000
---
# Backend for test upstream
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: envoy-ai-gateway-basic-testupstream
  namespace: default
spec:
  endpoints:
  - fqdn:
      hostname: httpbin.org
      port: 80
