apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: kubeflow
  annotations:
    serving.kserve.io/s3-endpoint: minio-service.kubeflow.svc.cluster.local:9000
    serving.kserve.io/s3-usehttps: "0"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
  namespace: kubeflow
secrets:
- name: minio-secret
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen-model
  namespace: kubeflow
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: huggingface
      storageUri: "s3://mlpipeline/v2/artifacts/qwen-model-security-pipeline/65630cfb-7b49-4a67-9557-1694afff1cb6/fetch-qwen-model/62f85cde-099e-4868-b12a-52de28ade85e/model_output"
      args:
        - --backend=huggingface
      resources:
        limits:
          cpu: "4"
          memory: 10Gi
        requests:
          cpu: "2"
          memory: 4Gi
