apiVersion: v1
kind: Namespace
metadata:
  name: kserve
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# -----------------------
# HelmRepository: Jetstack (Cert-Manager)
# -----------------------
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
# -----------------------
# HelmRepository: KServe OCI
# -----------------------
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kserve-oci
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/kserve/charts
  type: oci
---
# ---------------------------------------------------------------------
# HelmRelease: Cert-Manager (Jetstack)
# ---------------------------------------------------------------------
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.18.2
  install:
    createNamespace: false
  timeout: 30m
  values:
    installCRDs: true
---
# ---------------------------------------------------------------------
# HelmRelease: KServe CRDs (install CRDs first)
# ---------------------------------------------------------------------
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve-crd
  namespace: kserve
spec:
  interval: 24h
  releaseName: kserve-crd
  targetNamespace: kserve
  chart:
    spec:
      chart: kserve-crd
      sourceRef:
        kind: HelmRepository
        name: kserve-oci
        namespace: flux-system
      version: v0.15.0
  install:
    createNamespace: false
  timeout: 30m
  dependsOn:
    - name: cert-manager
  values: {}
---
# ---------------------------------------------------------------------
# HelmRelease: KServe (main) with Gateway API disabled (in-cluster only)
# ---------------------------------------------------------------------
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve
  namespace: kserve
spec:
  interval: 24h
  releaseName: kserve
  targetNamespace: kserve
  chart:
    spec:
      chart: kserve
      sourceRef:
        kind: HelmRepository
        name: kserve-oci
        namespace: flux-system
      version: v0.15.0
  install:
    createNamespace: false
  timeout: 30m
  dependsOn:
    - name: kserve-crd
  values:
    kserve:
      controller:
        deploymentMode: RawDeployment
        gateway:
          ingressGateway:
            enableGatewayApi: false
            kserveGateway: ""
