apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: vllm-runtime
spec:
  supportedModelFormats:
    - name: huggingface
      version: "1"
      autoSelect: true
  containers:
    - name: kserve-container
      image: kserve/vllmserver:latest
      args:
        - --model
        - /mnt/models
        - --served-model-name
        - "{{.Name}}"
        - --port
        - "8080"
        - --host
        - "0.0.0.0"
        - --tensor-parallel-size
        - "1"
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: HUGGINGFACE_HUB_CACHE
          value: /tmp/huggingface
        - name: TRANSFORMERS_CACHE
          value: /tmp/huggingface
      resources:
        requests:
          cpu: 2
          memory: 4Gi
        limits:
          cpu: 4
          memory: 20Gi
      volumeMounts:
        - name: model-cache
          mountPath: /tmp/huggingface
  volumes:
    - name: model-cache
      emptyDir: {}
